baseURL = "https://danbirman.com/blog/public/"
languageCode = "en-us"
title = "Lava Cake Expedition"
theme = "singular"

[params]
    author = "Dan Birman"
    description = "One lava cake for each volcano"
    githubUsername = "#"
    accent = "#F7342B"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    [params.logo]
        url = "/static/Volcano_Blog.gif"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:danbirman@gmail.com"
    name = "fas fa-envelope"
    weight = 1

#[[menu.icon]]
#    url = "https://github.com/dbirman/"
#    name = "fab fa-github"
#    weight = 2
